### ISSUE TITLE
./create_atomgroup.sh: line 14: /home/center/opt/aarch64/apps/amber/19.0/bin/cpptraj: cannot execute binary file

### ISSUE THREAD

**Issue by passive-radio** [flat35hd99/md_template#4]
Dear @flat35hd99

I faced an error when running 0structure/create_atomgroups.sh to generate files that are needed at step5 CURP calculation.

### terminal says
```
./create_atomgroup.sh: line 14: /home/center/opt/aarch64/apps/amber/19.0/bin/cpptraj: cannot execute binary file
```
(the terminal output is long enough to cover a whole screen, so please refer `terminal_output.txt` attached for more detailed output.)
[terminal_output.txt](https://github.com/flat35hd99/md_template/files/8372076/terminal_output.txt)

### create_atomgroups.sh
```bash: create_atomgroups.sh
#!/bin/sh -xeu
#PJM -L rscgrp=fx-debug
#PJM -L elapse=02:00:00
#PJM --mpi proc=1
#PJM -j

prefix=$PREFIX_7R98

source $prefix/util/load_amber
module load python/3.7.7

cd $prefix/0structure

cpptraj -i input/atominfo.cpptraj # <= line 14

python3 generate_atomgroup_sidechain.py \
    --sidechain-filename output/atomgroup_side.dat \
    --residue-filename output/atomgroup_residue.dat \
    --atominfo-filename output/atominfo.dat
```

### input/atom_info.cpptraj
```cpptraj:
parm output/system.dry.prmtop
atominfo out output/atominfo.dat
quit
```
I looked in http://archive.ambermd.org/ and etc.. to find out the solution but failed.
I hope that I can go thorough this step.

Thank you

**Comment by flat35hd99** [comment]
@passive-radio I'm surprised your high motivation !
The `create_atomgroup.sh` is job file for type 1 node. So, please login type 1 node (I assume that you can do that by `ssh f1` on local ) then

```
cd 0structure/log
pjsub ../create_atomgroup.sh
```

## Why the command failed?

Because the binary is suitable for aarch64, not x86. All login node and calculation node without type 1 has x86. Only calculation node of type 1 has aarch64. If you run `source load_amber`, then Amber for aarch64 is in `PATH`. So, the running failed.

**Comment by flat35hd99** [comment]
Unfortunately, you don't have enough time to get CURP calculation result. The calculation takes 1 or 2 days but the limit does not allow you to do that.

I recommend you to download all your calculation into local. If you don't have disk space, we have. Please let me know.

**Comment by passive-radio** [comment]
@flat35hd99 Thank you for your response.
But I had tried running the scripts on type1 node and the error appeared🤔

Though I wouldn't manage to get the final result, I've learned a lot and I'll be sure to download all the outputs from the calculations.

Thank you!

> @passive-radio I'm surprised your high motivation !
> 
> The `create_atomgroup.sh` is job file for type 1 node. So, please login type 1 node (I assume that you can do that by `ssh f1` on local ) then
> 
> 
> 
> ```
> 
> cd 0structure/log
> 
> pjsub ../create_atomgroup.sh
> 
> ```
> 
> 
> 
> ## Why the command failed?
> 
> 
> 
> Because the binary is suitable for aarch64, not x86. All login node and calculation node without type 1 has x86. Only calculation node of type 1 has aarch64. If you run `source load_amber`, then Amber for aarch64 is in `PATH`. So, the running failed.

**Comment by flat35hd99** [comment]
メール見てね！！！ @passive-radio
